# Generated by Django 6.0.1 on 2026-01-26 06:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TankClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('tier', models.IntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3'), (4, 'Tier 4'), (5, 'Tier 5'), (6, 'Tier 6'), (7, 'Tier 7'), (8, 'Tier 8'), (9, 'Tier 9'), (10, 'Tier 10')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='tanks/')),
                ('hp', models.PositiveIntegerField(default=0)),
                ('damage', models.PositiveIntegerField(default=0)),
                ('penetration', models.PositiveIntegerField(default=0)),
                ('armor', models.PositiveIntegerField(default=0)),
                ('speed', models.PositiveIntegerField(default=0)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='main.nation')),
                ('tank_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='main.tankclass')),
            ],
        ),
    ]
